/**
 * 应用常量定义
 */

// 对话历史配置
export const CONVERSATION_CONFIG = {
  MAX_HISTORY_MESSAGES: 10,
  MAX_HISTORY_FOR_ENHANCEMENT: 3,
  MAX_RECENT_CONVERSATIONS: 10,
} as const;

// AI 模型配置
export const AI_MODEL_CONFIG = {
  DEFAULT_MODEL: 'qwen3-32b',
  FAST_MODEL: 'Qwen/Qwen2.5-7B-Instruct',
  QWEN_MODEL: 'Qwen/Qwen3-32B',
  FALLBACK_QWEN_MODEL: 'Qwen/Qwen2.5-32B-Instruct',
  MAX_RETRIES: 3,
  BASE_RETRY_DELAY: 1000,
  BASE_TIMEOUT: 60000,
  INDEXING_TASK_TIMEOUT: 120000,
  KEYWORD_TASK_TIMEOUT: 20000,
  TIMEOUT_INCREMENT_PER_RETRY: 10000,
  MAX_TOKENS: 8192,
  DEFAULT_TEMPERATURE: 0.7,
  DEEP_THINKING_TEMPERATURE: 0.5,
} as const;

